export const sections = {
  arts: "arts",
  books: "books",
  business: "business",
  fashion: "fashion",
  food: "food",
  health: "health",
  home: "home",
  insider: "insider",
  magazine: "magazine",
  movies: "movies",
  opinion: "opinion",
  politics: "politics",
  science: "science",
  sports: "sports",
  technology: "technology",
  theater: "theater",
  travel: "travel",
  us: "us",
  world: "world",
}
